// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workload.proto

package org.apache.cassandra.grpc;

public interface ReadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:workloadgenerator.workload.ReadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
