// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workload.proto

package org.apache.cassandra.grpc;

public final class WorkloadProto {
  private WorkloadProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_workloadgenerator_workload_ReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_workloadgenerator_workload_ReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_workloadgenerator_workload_ReadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_workloadgenerator_workload_ReadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_workloadgenerator_workload_WriteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_workloadgenerator_workload_WriteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_workloadgenerator_workload_WriteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_workloadgenerator_workload_WriteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016workload.proto\022\032workloadgenerator.work" +
      "load\"\032\n\013ReadRequest\022\013\n\003key\030\001 \001(\t\"\035\n\014Read" +
      "Response\022\r\n\005value\030\001 \001(\t\"*\n\014WriteRequest\022" +
      "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\" \n\rWriteResp" +
      "onse\022\017\n\007success\030\001 \001(\0102\303\001\n\010Workload\022Y\n\004Re" +
      "ad\022\'.workloadgenerator.workload.ReadRequ" +
      "est\032(.workloadgenerator.workload.ReadRes" +
      "ponse\022\\\n\005Write\022(.workloadgenerator.workl" +
      "oad.WriteRequest\032).workloadgenerator.wor" +
      "kload.WriteResponseB,\n\031org.apache.cassan" +
      "dra.grpcB\rWorkloadProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_workloadgenerator_workload_ReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_workloadgenerator_workload_ReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_workloadgenerator_workload_ReadRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_workloadgenerator_workload_ReadResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_workloadgenerator_workload_ReadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_workloadgenerator_workload_ReadResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_workloadgenerator_workload_WriteRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_workloadgenerator_workload_WriteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_workloadgenerator_workload_WriteRequest_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_workloadgenerator_workload_WriteResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_workloadgenerator_workload_WriteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_workloadgenerator_workload_WriteResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
