// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workload.proto

package org.apache.cassandra.grpc;

public interface WriteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:workloadgenerator.workload.WriteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
